// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHCMt6Z0u_WC6aYfULhs5aVERWmDGWKQ8',
    appId: '1:635886397092:web:b358872a9d9d06042b2831',
    messagingSenderId: '635886397092',
    projectId: 'advanced-fff19',
    authDomain: 'advanced-fff19.firebaseapp.com',
    storageBucket: 'advanced-fff19.firebasestorage.app',
    measurementId: 'G-9F81PEXKMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7SHQ-C0RD01bSuvEU_eHq7EBq_KBNxlQ',
    appId: '1:635886397092:android:56330f34afb9651c2b2831',
    messagingSenderId: '635886397092',
    projectId: 'advanced-fff19',
    storageBucket: 'advanced-fff19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQoF6hFBsuW-la9pU77mgKgex0zXwcA4g',
    appId: '1:635886397092:ios:63a6418a0a689cbc2b2831',
    messagingSenderId: '635886397092',
    projectId: 'advanced-fff19',
    storageBucket: 'advanced-fff19.firebasestorage.app',
    iosBundleId: 'com.example.advancedcourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQoF6hFBsuW-la9pU77mgKgex0zXwcA4g',
    appId: '1:635886397092:ios:63a6418a0a689cbc2b2831',
    messagingSenderId: '635886397092',
    projectId: 'advanced-fff19',
    storageBucket: 'advanced-fff19.firebasestorage.app',
    iosBundleId: 'com.example.advancedcourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHCMt6Z0u_WC6aYfULhs5aVERWmDGWKQ8',
    appId: '1:635886397092:web:b376e95499ae4d522b2831',
    messagingSenderId: '635886397092',
    projectId: 'advanced-fff19',
    authDomain: 'advanced-fff19.firebaseapp.com',
    storageBucket: 'advanced-fff19.firebasestorage.app',
    measurementId: 'G-KDYYMF8EQZ',
  );
}
